version: '3.8'

networks:
  sigh_motos_default:
    external: true

services:
  sigc_redis:
    image: redis:7-alpine
    container_name: sigc_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - sigh_motos_redis_data:/data
    networks:
      - sigh_motos_default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sigh_motos_redis_data:
    external: true
