server {
    listen 80;
    server_name localhost;

    # Health check
    location /health {
        return 200 '{"status":"ok","gateway":"nginx"}';
        add_header Content-Type application/json;
    }

    # Inventory Service
    location /api/v1/products {
        proxy_pass http://sigc_inventory_service:3003/api/v1/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/brands {
        proxy_pass http://sigc_inventory_service:3003/api/v1/brands;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/categories {
        proxy_pass http://sigc_inventory_service:3003/api/v1/categories;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Notification Service - ruta exacta
    location /api/v1/notifications/send {
        proxy_pass http://sigc_notification_service:3004/api/v1/notifications/send;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Content-Type application/json;
    }

    # Notifications list
    location /api/v1/notifications {
        proxy_pass http://sigc_notification_service:3004/api/v1/notifications;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Report Service - ruta exacta
    location /api/v1/reports/kpis {
        proxy_pass http://sigc_report_service:3005/api/v1/reports/kpis;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Fallback al monolito
    location / {
        proxy_pass http://sigc_app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
