server {
    listen 80;
    server_name localhost;

    location /health {
        return 200 '{"status":"ok","gateway":"nginx"}';
        add_header Content-Type application/json;
    }

    location /api/v1/products {
        proxy_pass http://sigc_inventory_service:3003/api/v1/products;
        proxy_set_header Host $host;
    }

    location /api/v1/brands {
        proxy_pass http://sigc_inventory_service:3003/api/v1/brands;
        proxy_set_header Host $host;
    }

    location /api/v1/categories {
        proxy_pass http://sigc_inventory_service:3003/api/v1/categories;
        proxy_set_header Host $host;
    }

    location /api/v1/notifications/send {
        proxy_pass http://sigc_notification_service:3004/api/v1/notifications/send;
        proxy_set_header Host $host;
        proxy_set_header Content-Type application/json;
    }

    location /api/v1/notifications {
        proxy_pass http://sigc_notification_service:3004/api/v1/notifications;
        proxy_set_header Host $host;
    }

    location /api/v1/reports/kpis {
        proxy_pass http://sigc_report_service:3005/api/v1/reports/kpis;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://sigc_app:3000;
        proxy_set_header Host $host;
    }
}
