import api from './api'
import type { CashRegister, TreasuryTransaction, CashMovement, BankDeposit, BankTransfer, InTransitMoney, DailyLiquidity, MonthlyTaxSummary, WithholdingCalculation, WithholdingType, BudgetVsActual, ExpenseCategory, CashFlowProjection, OverdueReceivable, ExecutiveKPIs } from '@/types'
export interface DailyReport { openingBalance?: number; totalSales: number; totalExpenses: number; closingBalance: number }
export interface OpenRegisterInput { openingBalance?: number; notes?: string }
export interface CloseRegisterInput { actualBalance?: number; notes?: string }
export interface ExpenseInput { concept: string; amount: number; paymentMethod?: string; cashRegisterId?: string }
function toNum(v: unknown): number { return parseFloat(String(v ?? 0)) || 0 }
function mapRegister(r: any): CashRegister { return { id: r.id, openedAt: r.openedAt, closedAt: r.closedAt ?? undefined, openingBalance: toNum(r.openingBalance), expectedBalance: r.expectedClosingBalance != null ? toNum(r.expectedClosingBalance) : undefined, actualBalance: r.closingBalance != null ? toNum(r.closingBalance) : undefined, difference: r.difference != null ? toNum(r.difference) : undefined, status: r.status ?? 'CLOSED', openedBy: r.openedBy?.name ?? undefined, closedBy: r.closedBy?.name ?? undefined, notes: r.notes ?? undefined } }
function mapTransaction(t: any): TreasuryTransaction { return { id: t.id, cashRegisterId: t.cashRegisterId ?? '', type: t.type === 'INCOME' ? 'INCOME' : 'EXPENSE', concept: t.description ?? t.category ?? '', amount: toNum(t.amount), paymentMethod: t.paymentMethod ?? 'CASH', createdBy: t.performedBy?.name ?? undefined, createdAt: t.timestamp ?? t.createdAt ?? '' } }
export const treasuryService = {
  getCurrentRegister: async (): Promise<CashRegister | null> => { try { const { data } = await api.get('/treasury/shift'); const payload = (data as any)?.data ?? data; if (!payload || !payload.id) return null; return mapRegister(payload); } catch { return null } },
  getTransactions: async (): Promise<TreasuryTransaction[]> => { try { const { data } = await api.get('/treasury/transactions', { params: { limit: 50 } }); const payload = (data as any)?.data ?? data; const list = Array.isArray(payload) ? payload : payload?.transactions ?? []; return list.map(mapTransaction); } catch { return [] } },
  getDailyReport: async (): Promise<DailyReport> => { const { data } = await api.get('/treasury/global-summary'); const payload = (data as any)?.data ?? data; return { openingBalance: toNum(payload.initialBalance), totalSales: toNum(payload.totalIncome), totalExpenses: toNum(payload.totalExpenses), closingBalance: toNum(payload.expectedBalance) } },
  openRegister: async (input: OpenRegisterInput): Promise<CashRegister> => { const { data } = await api.post('/treasury/cash-register/open', { openingBalance: input.openingBalance, notes: input.notes }); const payload = (data as any)?.data ?? data; return mapRegister(payload) },
  closeRegister: async (id: string, input: CloseRegisterInput): Promise<CashRegister> => { const { data } = await api.post(`/treasury/cash-register/${id}/close`, { actualBalance: input.actualBalance, notes: input.notes }); const payload = (data as any)?.data ?? data; const register = payload?.cashRegister ?? payload; return mapRegister(register) },
  createExpense: async (input: ExpenseInput): Promise<void> => { await api.post('/treasury/expenses', { description: input.concept, category: 'Gasto Operativo', amount: input.amount, paymentMethod: input.paymentMethod }) },
  getCashMovements: async (date?: string): Promise<CashMovement[]> => { try { const params = date ? { date } : {}; const { data } = await api.get('/treasury/cash-movements', { params }); const payload = (data as any)?.data ?? data; return Array.isArray(payload) ? payload : []; } catch { return [] } },
  createDeposit: async (input: { amount: number; bankName: string; depositDate: string; accountNumber?: string; reference?: string; notes?: string; cashRegisterId?: string }): Promise<BankDeposit> => { const { data } = await api.post('/treasury/deposits', input); return ((data as any)?.data ?? data) as BankDeposit },
  updateDepositStatus: async (id: string, status: string): Promise<BankDeposit> => { const { data } = await api.patch(`/treasury/deposits/${id}/status`, { status }); return ((data as any)?.data ?? data) as BankDeposit },
  getDeposits: async (date?: string): Promise<BankDeposit[]> => { try { const params = date ? { date } : {}; const { data } = await api.get('/treasury/deposits', { params }); const payload = (data as any)?.data ?? data; return Array.isArray(payload) ? payload : []; } catch { return [] } },
  createBankTransfer: async (input: { fromAccount: string; toAccount: string; amount: number; description: string; reference?: string }): Promise<BankTransfer> => { const { data } = await api.post('/treasury/bank-transfers', input); return ((data as any)?.data ?? data) as BankTransfer },
  getBankTransfers: async (date?: string): Promise<BankTransfer[]> => { try { const params = date ? { date } : {}; const { data } = await api.get('/treasury/bank-transfers', { params }); const payload = (data as any)?.data ?? data; return Array.isArray(payload) ? payload : []; } catch { return [] } },
  getInTransitMoney: async (date?: string): Promise<InTransitMoney> => { const params = date ? { date } : {}; const { data } = await api.get('/treasury/in-transit', { params }); return ((data as any)?.data ?? data) as InTransitMoney },
  getDailyLiquidity: async (date?: string): Promise<DailyLiquidity> => { const params = date ? { date } : {}; const { data } = await api.get('/treasury/daily-liquidity', { params }); return ((data as any)?.data ?? data) as DailyLiquidity },
  getTaxSummary: async (month?: number, year?: number): Promise<MonthlyTaxSummary> => { const now = new Date(); const params = { month: month ?? now.getMonth() + 1, year: year ?? now.getFullYear() }; const { data } = await api.get('/treasury/tax-summary', { params }); return ((data as any)?.data ?? data) as MonthlyTaxSummary },
  calculateWithholding: async (type: WithholdingType, baseAmount: number): Promise<WithholdingCalculation> => { const { data } = await api.get('/treasury/withholding-calc', { params: { type, baseAmount } }); return ((data as any)?.data ?? data) as WithholdingCalculation },
  setBudget: async (input: { category: ExpenseCategory; month: number; year: number; amount: number }): Promise<void> => { await api.post('/treasury/budgets', input) },
  getBudgetVsActual: async (month?: number, year?: number): Promise<BudgetVsActual> => { const now = new Date(); const params = { month: month ?? now.getMonth() + 1, year: year ?? now.getFullYear() }; const { data } = await api.get('/treasury/budgets', { params }); return ((data as any)?.data ?? data) as BudgetVsActual },
  getCashFlowProjection: async (days = 7): Promise<CashFlowProjection> => { const { data } = await api.get('/treasury/cash-flow-projection', { params: { days } }); return ((data as any)?.data ?? data) as CashFlowProjection },
  getOverdueReceivables: async (): Promise<{ items: OverdueReceivable[]; totalOverdue: number; count: number }> => { const { data } = await api.get('/treasury/overdue-receivables'); return ((data as any)?.data ?? data) as { items: OverdueReceivable[]; totalOverdue: number; count: number } },
  getExecutiveKPIs: async (): Promise<ExecutiveKPIs> => { const { data } = await api.get('/treasury/executive-kpis'); return ((data as any)?.data ?? data) as ExecutiveKPIs },
}
