import { useState, useEffect, useCallback } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Landmark, Lock, Unlock, Download, TrendingUp, TrendingDown, DollarSign, RefreshCw, Banknote, AlertTriangle, ArrowRight, Calendar, BarChart3, Receipt, PiggyBank, Building2, ChevronUp, ChevronDown } from 'lucide-react'
import { toast } from 'sonner'
import { treasuryService } from '@/services/treasuryService'
import type { CashRegister, CashMovement, BankDeposit, DailyLiquidity, CashFlowProjection, OverdueReceivable, MonthlyTaxSummary, BudgetVsActual, ExecutiveKPIs } from '@/types'
import { openCashRegisterSchema, closeCashRegisterSchema, expenseSchema, type OpenCashRegisterInput, type CloseCashRegisterInput, type ExpenseInput } from '@/utils/validators'
import { PageHeader } from '@/components/ui/PageHeader'
import { Card, CardHeader, KpiCard } from '@/components/ui/Card'
import { Modal } from '@/components/ui/Modal'
import { Badge } from '@/components/ui/Badge'
import { Spinner } from '@/components/ui/Spinner'
import { TableSkeleton } from '@/components/ui/Skeleton'
import { formatCOP, formatDateTime } from '@/utils/formatters'
import { generateDailyCashFlowPDF } from '@/utils/pdfGenerator'
const PAYMENT_METHODS = [{ value: 'CASH', label: 'Efectivo' }, { value: 'CARD', label: 'Tarjeta' }, { value: 'TRANSFER', label: 'Transferencia' }, { value: 'NEQUI', label: 'Nequi' }, { value: 'DAVIPLATA', label: 'Daviplata' }, { value: 'MIXED', label: 'Mixto' }]
const PM_LABEL: Record<string, string> = { CASH: 'Efectivo', CARD: 'Tarjeta', TRANSFER: 'Transferencia', MIXED: 'Mixto', CREDIT: 'Crédito', NEQUI: 'Nequi', DAVIPLATA: 'Daviplata' }
const DEPOSIT_STATUS_LABEL: Record<string, string> = { PENDING: 'Pendiente', IN_TRANSIT: 'En Tránsito', RECONCILED: 'Conciliado', REJECTED: 'Rechazado' }
const DEPOSIT_STATUS_COLOR: Record<string, string> = { PENDING: 'badge-yellow', IN_TRANSIT: 'badge-blue', RECONCILED: 'badge-green', REJECTED: 'badge-red' }
type Tab = 'caja' | 'liquidez' | 'proyeccion' | 'fiscal'
function todayISO(): string { return new Date().toISOString().split('T')[0]! }
interface DailyReport { openingBalance: number; totalSales: number; totalExpenses: number; expectedBalance: number }
export default function Treasury() {
  const [activeTab, setActiveTab] = useState<Tab>('caja')
  const [currentRegister, setCurrentRegister] = useState<CashRegister | null>(null)
  const [dailyReport, setDailyReport] = useState<DailyReport | null>(null)
  const [cashMovements, setCashMovements] = useState<CashMovement[]>([])
  const [executiveKPIs, setExecutiveKPIs] = useState<ExecutiveKPIs | null>(null)
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [deposits, setDeposits] = useState<BankDeposit[]>([])
  const [dailyLiquidity, setDailyLiquidity] = useState<DailyLiquidity | null>(null)
  const [liquidityLoading, setLiquidityLoading] = useState(false)
  const [cashFlow, setCashFlow] = useState<CashFlowProjection | null>(null)
  const [overdueItems, setOverdueItems] = useState<OverdueReceivable[]>([])
  const [projectionLoading, setProjectionLoading] = useState(false)
  const [taxSummary, setTaxSummary] = useState<MonthlyTaxSummary | null>(null)
  const [budget, setBudgetData] = useState<BudgetVsActual | null>(null)
  const [fiscalLoading, setFiscalLoading] = useState(false)
  const [openModal, setOpenModal] = useState(false)
  const [closeModal, setCloseModal] = useState(false)
  const [expenseModal, setExpenseModal] = useState(false)
  const [depositModal, setDepositModal] = useState(false)
  const [saving, setSaving] = useState(false)
  const [depositForm, setDepositForm] = useState({ amount: '', bankName: '', accountNumber: '', reference: '', notes: '', depositDate: todayISO() })
  const { register: regOpen, handleSubmit: handleOpenSubmit, reset: resetOpen, formState: { errors: openErrors } } = useForm<OpenCashRegisterInput>({ resolver: zodResolver(openCashRegisterSchema), defaultValues: { openingBalance: 0 } })
  const { register: regClose, handleSubmit: handleCloseSubmit, reset: resetClose, formState: { errors: closeErrors } } = useForm<CloseCashRegisterInput>({ resolver: zodResolver(closeCashRegisterSchema) })
  const { register: regExp, handleSubmit: handleExpSubmit, reset: resetExp, formState: { errors: expErrors } } = useForm<ExpenseInput>({ resolver: zodResolver(expenseSchema), defaultValues: { paymentMethod: 'CASH' } })
  const load = useCallback(async (silent = false) => { if (!silent) setLoading(true); else setRefreshing(true); try { const [regResult, reportResult, movResult, kpiResult] = await Promise.allSettled([ treasuryService.getCurrentRegister(), treasuryService.getDailyReport(), treasuryService.getCashMovements(), treasuryService.getExecutiveKPIs() ]); if (regResult.status === 'fulfilled') setCurrentRegister(regResult.value); if (movResult.status === 'fulfilled') setCashMovements(movResult.value); if (kpiResult.status === 'fulfilled') setExecutiveKPIs(kpiResult.value); if (reportResult.status === 'fulfilled' && reportResult.value) { const r = reportResult.value; setDailyReport({ openingBalance: r.openingBalance, totalSales: r.totalSales, totalExpenses: r.totalExpenses, expectedBalance: r.closingBalance }) } } catch {} finally { setLoading(false); setRefreshing(false) } }, [])
  const loadLiquidity = useCallback(async () => { setLiquidityLoading(true); try { const [depResult, liqResult] = await Promise.allSettled([ treasuryService.getDeposits(), treasuryService.getDailyLiquidity() ]); if (depResult.status === 'fulfilled') setDeposits(depResult.value); if (liqResult.status === 'fulfilled') setDailyLiquidity(liqResult.value) } catch {} finally { setLiquidityLoading(false) } }, [])
  const loadProjection = useCallback(async () => { setProjectionLoading(true); try { const [cfResult, ovResult] = await Promise.allSettled([ treasuryService.getCashFlowProjection(7), treasuryService.getOverdueReceivables() ]); if (cfResult.status === 'fulfilled') setCashFlow(cfResult.value); if (ovResult.status === 'fulfilled' && ovResult.value) setOverdueItems(ovResult.value.items) } catch {} finally { setProjectionLoading(false) } }, [])
  const loadFiscal = useCallback(async () => { setFiscalLoading(true); try { const [taxResult, budgetResult] = await Promise.allSettled([ treasuryService.getTaxSummary(), treasuryService.getBudgetVsActual() ]); if (taxResult.status === 'fulfilled') setTaxSummary(taxResult.value); if (budgetResult.status === 'fulfilled') setBudgetData(budgetResult.value) } catch {} finally { setFiscalLoading(false) } }, [])
  useEffect(() => { load() }, [load])
  useEffect(() => { if (activeTab === 'liquidez' && !dailyLiquidity) loadLiquidity(); if (activeTab === 'proyeccion' && !cashFlow) loadProjection(); if (activeTab === 'fiscal' && !taxSummary) loadFiscal() }, [activeTab, dailyLiquidity, cashFlow, taxSummary, loadLiquidity, loadProjection, loadFiscal])
  const onOpenRegister = async (data: OpenCashRegisterInput) => { setSaving(true); try { const reg = await treasuryService.openRegister(data as OpenCashRegisterInput); setCurrentRegister(reg); toast.success('Caja abierta'); setOpenModal(false); resetOpen(); load() } catch (err: unknown) { toast.error((err as any)?.response?.data?.error ?? 'Error') } finally { setSaving(false) } }
  const onCloseRegister = async (data: CloseCashRegisterInput) => { if (!currentRegister) return; setSaving(true); try { const reg = await treasuryService.closeRegister(currentRegister.id, data as CloseCashRegisterInput); setCurrentRegister(reg); toast.success('Caja cerrada. Generando PDF...'); setCloseModal(false); resetClose(); await load(); const latestMovements = await treasuryService.getCashMovements(); const report = dailyReport ?? { openingBalance: 0, totalSales: 0, totalExpenses: 0, expectedBalance: 0 }; generateDailyCashFlowPDF(reg, report, latestMovements, todayISO()) } catch (err: unknown) { toast.error((err as any)?.response?.data?.error ?? 'Error') } finally { setSaving(false) } }
  const onCreateExpense = async (data: Partial<ExpenseInput>) => { setSaving(true); try { await treasuryService.createExpense({ concept: data.concept || 'Gasto Operativo', amount: data.amount || 0, paymentMethod: data.paymentMethod || 'CASH', cashRegisterId: currentRegister?.id }); toast.success('Gasto registrado'); setExpenseModal(false); resetExp(); load(true) } catch (err: unknown) { toast.error((err as any)?.response?.data?.error ?? 'Error') } finally { setSaving(false) } }
  const onCreateDeposit = async () => { if (!depositForm.amount || !depositForm.bankName) { toast.warning('Monto y banco requeridos'); return } setSaving(true); try { await treasuryService.createDeposit({ amount: parseFloat(depositForm.amount), bankName: depositForm.bankName, depositDate: depositForm.depositDate, accountNumber: depositForm.accountNumber || undefined, reference: depositForm.reference || undefined, notes: depositForm.notes || undefined, cashRegisterId: currentRegister?.id }); toast.success('Depósito registrado'); setDepositModal(false); setDepositForm({ amount: '', bankName: '', accountNumber: '', reference: '', notes: '', depositDate: todayISO() }); loadLiquidity() } catch (err: unknown) { toast.error((err as any)?.response?.data?.error ?? 'Error') } finally { setSaving(false) } }
  const handleDownloadPDF = () => { if (!dailyReport) { toast.warning('Sin datos'); return } generateDailyCashFlowPDF(currentRegister, dailyReport, cashMovements, todayISO()); toast.success('PDF generado') }
  const handleUpdateDepositStatus = async (id: string, status: string) => { try { await treasuryService.updateDepositStatus(id, status); toast.success('Estado actualizado'); loadLiquidity() } catch { toast.error('Error') } }
  const isOpen = currentRegister?.status === 'OPEN'; const difference = currentRegister?.difference ?? 0; const totalIngresos = cashMovements.filter(m => m.type === 'INGRESO').reduce((s, m) => s + m.amount, 0); const totalEgresos = cashMovements.filter(m => m.type === 'EGRESO').reduce((s, m) => s + m.amount, 0)
  return (<div>
    <PageHeader title="Tesorería" description="Control bancario de precisión" actions={<div className="flex gap-2 flex-wrap">
      <button type="button" className="btn-outline btn-sm" onClick={() => { load(true); if (activeTab === 'liquidez') loadLiquidity(); if (activeTab === 'proyeccion') loadProjection(); if (activeTab === 'fiscal') loadFiscal() }} disabled={refreshing}><RefreshCw className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`} /></button>
      {isOpen && (<>
        <button type="button" className="btn-outline btn-sm" onClick={handleDownloadPDF}><Download className="w-4 h-4" /> PDF</button>
        <button type="button" className="btn-outline btn-sm" onClick={() => setDepositModal(true)}><Building2 className="w-4 h-4" /> Depósito</button>
        <button type="button" className="btn-outline btn-sm" onClick={() => { resetExp(); setExpenseModal(true) }}><TrendingDown className="w-4 h-4" /> Gasto</button>
        <button type="button" className="btn-destructive btn-sm" onClick={() => { resetClose(); setCloseModal(true) }}><Lock className="w-4 h-4" /> Cerrar Caja</button>
      </>)}
      {!isOpen && (<button type="button" className="btn-primary btn-sm" onClick={() => { resetOpen(); setOpenModal(true) }}><Unlock className="w-4 h-4" /> Abrir Caja</button>)}
    </div>} />
    <div className="flex gap-1 bg-gray-100 rounded-xl p-1 mb-6 overflow-x-auto">
      {([{ id: 'caja', label: 'Caja Diaria', icon: <Banknote className="w-4 h-4" /> }, { id: 'liquidez', label: 'Liquidez', icon: <Building2 className="w-4 h-4" /> }, { id: 'proyeccion', label: 'Flujo de Caja', icon: <BarChart3 className="w-4 h-4" /> }, { id: 'fiscal', label: 'Fiscal', icon: <Receipt className="w-4 h-4" /> }] as { id: Tab; label: string; icon: React.ReactNode }[]).map(tab => (<button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-medium transition-all whitespace-nowrap flex-1 justify-center ${activeTab === tab.id ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}>{tab.icon} {tab.label}</button>))}
    </div>
    {activeTab === 'caja' && (<>
      {loading ? (<div className="h-24 bg-white rounded-xl border border-gray-200 animate-pulse mb-6" />) : currentRegister ? (<Card className="mb-6 p-5"><div className="flex items-center justify-between flex-wrap gap-4"><div className="flex items-center gap-4"><div className={`w-12 h-12 rounded-full flex items-center justify-center ${isOpen ? 'bg-green-100' : 'bg-gray-100'}`}>{isOpen ? <Unlock className="w-6 h-6 text-green-600" /> : <Lock className="w-6 h-6 text-gray-500" />}</div><div><p className="font-semibold text-gray-900">Caja {isOpen ? 'Abierta' : 'Cerrada'}<span className={`ml-2 text-xs font-medium px-2 py-0.5 rounded-full ${isOpen ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'}`}>{isOpen ? 'EN OPERACIÓN' : 'CERRADA'}</span></p><p className="text-sm text-gray-500">Apertura: {formatDateTime(currentRegister.openedAt)}{currentRegister.openedBy && ` · ${currentRegister.openedBy}`}</p>{currentRegister.closedAt && (<p className="text-sm text-gray-400">Cierre: {formatDateTime(currentRegister.closedAt)}{currentRegister.closedBy && ` · ${currentRegister.closedBy}`}</p>)}</div></div><div className="text-right"><p className="text-xs text-gray-400 uppercase tracking-wide">Saldo Apertura</p><p className="text-2xl font-bold text-gray-900">{formatCOP(currentRegister.openingBalance)}</p></div></div></Card>) : (<Card className="mb-6 p-8 text-center"><Landmark className="w-12 h-12 text-gray-300 mx-auto mb-3" /><p className="text-gray-500 font-medium">No hay caja activa</p><button type="button" className="btn-primary btn-sm mt-4" onClick={() => { resetOpen(); setOpenModal(true) }}><Unlock className="w-4 h-4" /> Abrir Caja Ahora</button></Card>)}
      <div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
        <KpiCard title="Saldo Inicial" value={formatCOP(dailyReport?.openingBalance ?? 0)} icon={<DollarSign />} color="blue" />
        <KpiCard title="Ventas del Día" value={formatCOP(dailyReport?.totalSales ?? 0)} icon={<TrendingUp />} color="green" />
        <KpiCard title="Gastos del Día" value={formatCOP(dailyReport?.totalExpenses ?? 0)} icon={<TrendingDown />} color="red" />
        <KpiCard title="Saldo Esperado" value={formatCOP(dailyReport?.expectedBalance ?? 0)} icon={<Landmark />} color="orange" />
      </div>
      {dailyReport && (<Card className="mb-6 p-4 bg-blue-50 border border-blue-200"><p className="text-sm font-medium text-blue-800 text-center"><span className="font-bold">Fórmula:</span> {formatCOP(dailyReport.openingBalance)} (inicial) <span className="text-green-700">+ {formatCOP(dailyReport.totalSales)} (ventas)</span> <span className="text-red-700">− {formatCOP(dailyReport.totalExpenses)} (gastos)</span> = <span className="font-bold text-blue-900">{formatCOP(dailyReport.expectedBalance)}</span></p></Card>)}
      {executiveKPIs && (<div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
        <div className="bg-white border border-gray-200 rounded-xl p-4"><p className="text-xs text-gray-500 uppercase tracking-wide">Ticket Promedio</p><p className="text-xl font-bold text-gray-900 mt-1">{formatCOP(executiveKPIs.today.avgTicket)}</p><p className="text-xs text-gray-400 mt-1">{executiveKPIs.today.transactionCount} transacciones</p></div>
        <div className="bg-white border border-gray-200 rounded-xl p-4"><p className="text-xs text-gray-500 uppercase tracking-wide">Rotación</p><p className="text-xl font-bold text-gray-900 mt-1">{executiveKPIs.today.rotationRatio.toFixed(2)}x</p><p className="text-xs text-gray-400 mt-1">ventas / saldo inicial</p></div>
        <div className={`border rounded-xl p-4 ${executiveKPIs.comparison.vsYesterday >= 0 ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'}`}><p className="text-xs text-gray-500 uppercase tracking-wide">vs Ayer</p><p className={`text-xl font-bold mt-1 ${executiveKPIs.comparison.vsYesterday >= 0 ? 'text-green-700' : 'text-red-600'}`}>{executiveKPIs.comparison.vsYesterday >= 0 ? '+' : ''}{executiveKPIs.comparison.vsYesterday.toFixed(1)}%</p><p className="text-xs text-gray-400 mt-1">en ventas</p></div>
        <div className="bg-white border border-gray-200 rounded-xl p-4"><p className="text-xs text-gray-500 uppercase tracking-wide">Autonomía</p><p className="text-xl font-bold text-gray-900 mt-1">{Math.min(executiveKPIs.liquidity.autonomyDays, 999).toFixed(0)} días</p><p className="text-xs text-gray-400 mt-1">con efectivo actual</p></div>
      </div>)}
      {currentRegister?.status === 'CLOSED' && (<Card className="mb-6 p-5 border-l-4 border-l-indigo-500"><h3 className="font-semibold text-gray-800 mb-3">Arqueo de Caja</h3><div className="grid grid-cols-3 gap-4 text-sm"><div><p className="text-gray-500 text-xs uppercase tracking-wide">Esperado</p><p className="font-bold text-lg">{formatCOP(currentRegister.expectedBalance ?? dailyReport?.expectedBalance ?? 0)}</p></div><div><p className="text-gray-500 text-xs uppercase tracking-wide">Real</p><p className="font-bold text-lg">{formatCOP(currentRegister.actualBalance ?? 0)}</p></div><div><p className="text-gray-500 text-xs uppercase tracking-wide">Diferencia</p><p className={`font-bold text-lg ${difference > 0 ? 'text-green-600' : difference < 0 ? 'text-red-600' : 'text-gray-900'}`}>{difference >= 0 ? '+' : ''}{formatCOP(difference)}</p><p className={`text-xs mt-1 font-medium ${Math.abs(difference) < 0.01 ? 'text-green-600' : difference > 0 ? 'text-green-600' : 'text-red-600'}`}>{Math.abs(difference) < 0.01 ? 'CUADRADO' : difference > 0 ? 'SOBRANTE' : 'FALTANTE'}</p></div></div></Card>)}
      <Card className="overflow-hidden"><CardHeader className="flex items-center justify-between"><div><h2 className="font-semibold text-gray-800">Movimientos</h2></div><div className="flex items-center gap-3"><div className="text-right text-xs text-gray-500 hidden sm:block"><p><span className="text-green-600 font-medium">↑ {formatCOP(totalIngresos)}</span> ingresos</p><p><span className="text-red-600 font-medium">↓ {formatCOP(totalEgresos)}</span> egresos</p></div><Badge variant={isOpen ? 'green' : 'gray'}>{cashMovements.length} movs</Badge></div></CardHeader><div className="overflow-x-auto">{loading ? (<TableSkeleton rows={6} cols={5} />) : cashMovements.length === 0 ? (<div className="py-16 text-center"><DollarSign className="w-10 h-10 text-gray-200 mx-auto mb-3" /><p className="text-gray-400 text-sm font-medium">Sin movimientos hoy</p></div>) : (<table className="w-full"><thead><tr className="bg-gray-50 border-b border-gray-200"><th className="table-th">Fecha</th><th className="table-th">Tipo</th><th className="table-th">Concepto</th><th className="table-th">Ref</th><th className="table-th">Método</th><th className="table-th text-right">Monto</th></tr></thead><tbody>{cashMovements.map((m) => (<tr key={m.id} className="table-row"><td className="table-td text-xs text-gray-500 whitespace-nowrap">{formatDateTime(m.timestamp)}</td><td className="table-td">{m.type === 'INGRESO' ? (<span className="badge-green flex items-center gap-1 w-fit text-xs"><TrendingUp className="w-3 h-3" /> Ingreso</span>) : (<span className="badge-red flex items-center gap-1 w-fit text-xs"><TrendingDown className="w-3 h-3" /> Gasto</span>)}</td><td className="table-td font-medium text-sm">{m.concept}</td><td className="table-td text-xs text-gray-400">{m.reference}</td><td className="table-td text-xs text-gray-500">{PM_LABEL[m.paymentMethod] ?? m.paymentMethod}</td><td className={`table-td font-semibold text-right whitespace-nowrap ${m.type === 'INGRESO' ? 'text-green-700' : 'text-red-600'}`}>{m.type === 'INGRESO' ? '+' : '−'}{formatCOP(m.amount)}</td></tr>))}</tbody><tfoot><tr className="bg-gray-50 border-t-2 border-gray-300"><td colSpan={5} className="table-td font-bold text-gray-700 text-sm">SALDO ESPERADO</td><td className="table-td font-bold text-gray-900 text-right text-xl">{formatCOP(dailyReport?.expectedBalance ?? 0)}</td></tr></tfoot></table>)}</div></Card>
    </>)}
    {activeTab === 'liquidez' && (<>
      {liquidityLoading ? (<div className="space-y-4">{[1, 2, 3].map(i => <div key={i} className="h-32 bg-white rounded-xl border border-gray-200 animate-pulse" />)}</div>) : (<>
        {dailyLiquidity && (<Card className="mb-6 p-5"><h2 className="font-semibold text-gray-800 mb-4 flex items-center gap-2"><PiggyBank className="w-5 h-5 text-blue-600" /> Liquidez</h2><div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-4">
          <div className="bg-green-50 border border-green-200 rounded-xl p-4"><p className="text-xs text-green-700 uppercase tracking-wide font-medium">Disponible Hoy</p><p className="text-2xl font-bold text-green-800 mt-1">{formatCOP(dailyLiquidity.availableToday)}</p></div>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4"><p className="text-xs text-amber-700 uppercase tracking-wide font-medium">En Tránsito</p><p className="text-2xl font-bold text-amber-800 mt-1">{formatCOP(dailyLiquidity.inTransitCard)}</p></div>
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-4"><p className="text-xs text-blue-700 uppercase tracking-wide font-medium">Depósitos Hoy</p><p className="text-2xl font-bold text-blue-800 mt-1">{formatCOP(dailyLiquidity.depositsToday)}</p></div>
          <div className="bg-red-50 border border-red-200 rounded-xl p-4"><p className="text-xs text-red-700 uppercase tracking-wide font-medium">Comisiones</p><p className="text-2xl font-bold text-red-800 mt-1">{formatCOP(dailyLiquidity.totalCommissions)}</p></div>
        </div>{dailyLiquidity.breakdown.length > 0 && (<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50 border-b border-gray-200"><th className="table-th">Método</th><th className="table-th text-right">Bruto</th><th className="table-th text-right">Comisión</th><th className="table-th text-right">Neto</th><th className="table-th">Disponibilidad</th></tr></thead><tbody>{dailyLiquidity.breakdown.map((b, i) => (<tr key={i} className="table-row"><td className="table-td font-medium">{PM_LABEL[b.paymentMethod] ?? b.paymentMethod}</td><td className="table-td text-right">{formatCOP(b.grossAmount)}</td><td className="table-td text-right text-red-600">{b.commission > 0 ? `−${formatCOP(b.commission)}` : '—'}</td><td className="table-td text-right font-semibold">{formatCOP(b.netAmount)}</td><td className="table-td">{b.available ? <span className="badge-green text-xs">Inmediato</span> : <span className="badge-yellow text-xs">24-48h</span>}</td></tr>))}</tbody></table></div>)}</Card>)}
        <Card className="overflow-hidden mb-6"><CardHeader className="flex items-center justify-between"><h2 className="font-semibold text-gray-800 flex items-center gap-2"><Building2 className="w-5 h-5 text-blue-600" /> Depósitos</h2><button type="button" className="btn-primary btn-sm" onClick={() => setDepositModal(true)}><Building2 className="w-4 h-4" /> Nuevo</button></CardHeader>{deposits.length === 0 ? (<div className="py-12 text-center text-gray-400 text-sm">Sin depósitos</div>) : (<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50 border-b border-gray-200"><th className="table-th">Fecha</th><th className="table-th">Banco</th><th className="table-th text-right">Monto</th><th className="table-th">Ref</th><th className="table-th">Estado</th><th className="table-th">Acciones</th></tr></thead><tbody>{deposits.map(d => (<tr key={d.id} className="table-row"><td className="table-td text-xs text-gray-500">{formatDateTime(d.depositDate)}</td><td className="table-td font-medium">{d.bankName}</td><td className="table-td text-right font-semibold text-blue-700">{formatCOP(Number(d.amount))}</td><td className="table-td text-xs text-gray-400">{d.reference ?? '—'}</td><td className="table-td"><span className={`badge text-xs ${DEPOSIT_STATUS_COLOR[d.status] ?? 'badge-gray'}`}>{DEPOSIT_STATUS_LABEL[d.status] ?? d.status}</span></td><td className="table-td">{d.status === 'PENDING' && (<button type="button" className="btn-outline btn-xs text-xs" onClick={() => handleUpdateDepositStatus(d.id, 'IN_TRANSIT')}><ArrowRight className="w-3 h-3" /> Tránsito</button>)}{d.status === 'IN_TRANSIT' && (<button type="button" className="btn-outline btn-xs text-xs" onClick={() => handleUpdateDepositStatus(d.id, 'RECONCILED')}><ArrowRight className="w-3 h-3" /> Conciliar</button>)}</td></tr>))}</tbody></table></div>)}</Card>
      </>)}
    </>)}
    {activeTab === 'proyeccion' && (<>
      {projectionLoading ? (<div className="space-y-4">{[1, 2].map(i => <div key={i} className="h-48 bg-white rounded-xl border border-gray-200 animate-pulse" />)}</div>) : (<>
        {cashFlow && (<>
          <div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
            <div className="bg-blue-50 border border-blue-200 rounded-xl p-4"><p className="text-xs text-blue-700 uppercase tracking-wide font-medium">Saldo Actual</p><p className="text-2xl font-bold text-blue-800 mt-1">{formatCOP(cashFlow.currentBalance)}</p></div>
            <div className={`border rounded-xl p-4 ${cashFlow.alertDays > 0 ? 'bg-red-50 border-red-200' : 'bg-green-50 border-green-200'}`}><p className={`text-xs uppercase tracking-wide font-medium ${cashFlow.alertDays > 0 ? 'text-red-700' : 'text-green-700'}`}>Días Críticos</p><p className={`text-2xl font-bold mt-1 ${cashFlow.alertDays > 0 ? 'text-red-800' : 'text-green-800'}`}>{cashFlow.alertDays}</p></div>
            <div className="bg-white border border-gray-200 rounded-xl p-4"><p className="text-xs text-gray-500 uppercase tracking-wide font-medium">Saldo Más Bajo</p><p className={`text-2xl font-bold mt-1 ${cashFlow.lowestBalance < 0 ? 'text-red-700' : 'text-gray-800'}`}>{formatCOP(cashFlow.lowestBalance)}</p></div>
            <div className="bg-white border border-gray-200 rounded-xl p-4"><p className="text-xs text-gray-500 uppercase tracking-wide font-medium">Horizonte</p><p className="text-2xl font-bold text-gray-800 mt-1">{cashFlow.projectionDays} días</p></div>
          </div>
          <Card className="overflow-hidden mb-6"><CardHeader><h2 className="font-semibold text-gray-800 flex items-center gap-2"><Calendar className="w-5 h-5 text-blue-600" /> Proyección (7 días)</h2></CardHeader><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50 border-b border-gray-200"><th className="table-th">Día</th><th className="table-th text-right">Inicial</th><th className="table-th text-right">CxC</th><th className="table-th text-right">CxP</th><th className="table-th text-right">Flujo</th><th className="table-th text-right">Final</th></tr></thead><tbody>{cashFlow.days.map(day => (<tr key={day.date} className={`table-row ${day.isAlert ? 'bg-red-50' : ''}`}><td className="table-td">{day.dayLabel}</td><td className="table-td text-right">{formatCOP(day.openingBalance)}</td><td className="table-td text-right text-green-700">{day.expectedInflows > 0 ? `+${formatCOP(day.expectedInflows)}` : '—'}</td><td className="table-td text-right text-red-600">{day.expectedOutflows > 0 ? `−${formatCOP(day.expectedOutflows)}` : '—'}</td><td className={`table-td text-right font-semibold ${day.netFlow >= 0 ? 'text-green-700' : 'text-red-600'}`}>{day.netFlow >= 0 ? '+' : ''}{formatCOP(day.netFlow)}</td><td className={`table-td text-right font-bold ${day.closingBalance < 0 ? 'text-red-700' : 'text-gray-900'}`}>{formatCOP(day.closingBalance)}</td></tr>))}</tbody></table></div></Card>
        </>)}
        <Card className="overflow-hidden"><CardHeader className="flex items-center justify-between"><h2 className="font-semibold text-gray-800 flex items-center gap-2"><AlertTriangle className="w-5 h-5 text-amber-500" /> CxC Vencidas</h2>{overdueItems.length > 0 && (<span className="badge-red text-xs">{overdueItems.length}</span>)}</CardHeader>{overdueItems.length === 0 ? (<div className="py-12 text-center text-gray-400 text-sm">Sin cuentas vencidas</div>) : (<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50 border-b border-gray-200"><th className="table-th">Cliente</th><th className="table-th">Venta</th><th className="table-th text-right">Saldo</th><th className="table-th text-right">Días</th><th className="table-th">Urgencia</th></tr></thead><tbody>{overdueItems.map(item => (<tr key={item.id} className="table-row"><td className="table-td font-medium">{item.customerName}</td><td className="table-td text-xs text-gray-500">{item.saleNumber}</td><td className="table-td text-right font-semibold text-red-700">{formatCOP(item.remainingBalance)}</td><td className="table-td text-right font-bold">{item.daysOverdue}d</td><td className="table-td"><span className={`badge text-xs ${item.urgency === 'CRITICAL' ? 'badge-red' : item.urgency === 'WARNING' ? 'badge-yellow' : 'badge-blue'}`}>{item.urgency}</span></td></tr>))}</tbody></table></div>)}</Card>
      </>)}
    </>)}
    {activeTab === 'fiscal' && (<>
      {fiscalLoading ? (<div className="space-y-4">{[1, 2].map(i => <div key={i} className="h-48 bg-white rounded-xl border border-gray-200 animate-pulse" />)}</div>) : (<>
        {taxSummary && (<Card className="mb-6 p-5"><h2 className="font-semibold text-gray-800 mb-4 flex items-center gap-2"><Receipt className="w-5 h-5 text-purple-600" /> Fiscal — {taxSummary.period.label}</h2><div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-4">
          <div className="bg-red-50 border border-red-200 rounded-xl p-4"><p className="text-xs text-red-700 uppercase tracking-wide font-medium">IVA Cobrado</p><p className="text-xl font-bold text-red-800 mt-1">{formatCOP(taxSummary.ivaCollected)}</p></div>
          <div className="bg-green-50 border border-green-200 rounded-xl p-4"><p className="text-xs text-green-700 uppercase tracking-wide font-medium">IVA Deducible</p><p className="text-xl font-bold text-green-800 mt-1">{formatCOP(taxSummary.ivaDeductible)}</p></div>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4"><p className="text-xs text-amber-700 uppercase tracking-wide font-medium">IVA Neto</p><p className="text-xl font-bold text-amber-800 mt-1">{formatCOP(taxSummary.ivaNetPayable)}</p></div>
          <div className={`border rounded-xl p-4 ${taxSummary.netObligations < 0 ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'}`}><p className={`text-xs uppercase tracking-wide font-medium ${taxSummary.netObligations < 0 ? 'text-green-700' : 'text-red-700'}`}>Obligación Neta</p><p className={`text-xl font-bold mt-1 ${taxSummary.netObligations < 0 ? 'text-green-800' : 'text-red-800'}`}>{formatCOP(taxSummary.netObligations)}</p></div>
        </div></Card>)}
        {budget && (<Card className="overflow-hidden"><CardHeader className="flex items-center justify-between"><h2 className="font-semibold text-gray-800 flex items-center gap-2"><BarChart3 className="w-5 h-5 text-blue-600" /> Presupuesto — {budget.period.label}</h2></CardHeader>{budget.lines.length === 0 ? (<div className="py-12 text-center text-gray-400 text-sm">Sin presupuesto</div>) : (<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50 border-b border-gray-200"><th className="table-th">Categoría</th><th className="table-th text-right">Presupuesto</th><th className="table-th text-right">Real</th><th className="table-th text-right">Disponible</th><th className="table-th">Ejecución</th></tr></thead><tbody>{budget.lines.map(line => (<tr key={line.category} className={`table-row ${line.isOverBudget ? 'bg-red-50' : line.isAlert ? 'bg-amber-50' : ''}`}><td className="table-td font-medium">{line.categoryLabel}</td><td className="table-td text-right">{formatCOP(line.budgeted)}</td><td className="table-td text-right font-semibold">{formatCOP(line.actual)}</td><td className={`table-td text-right font-semibold ${line.remaining < 0 ? 'text-red-600' : 'text-green-700'}`}>{formatCOP(line.remaining)}</td><td className="table-td"><div className="flex items-center gap-2"><div className="flex-1 bg-gray-200 rounded-full h-2 min-w-16"><div className={`h-2 rounded-full ${line.isOverBudget ? 'bg-red-500' : line.isAlert ? 'bg-amber-500' : 'bg-green-500'}`} style={{ width: `${Math.min(100, line.executionPct)}%` }} /></div><span className={`text-xs font-medium ${line.isOverBudget ? 'text-red-600' : line.isAlert ? 'text-amber-600' : 'text-gray-600'}`}>{line.executionPct.toFixed(0)}%</span></div></td></tr>))}</tbody></table></div>)}</Card>)}
      </>)}
    </>)}
    {/* MODALES */}
    <Modal open={openModal} onClose={() => setOpenModal(false)} title="Abrir Caja" size="sm" footer={<div className="flex justify-end gap-2"><button type="button" className="btn-outline" onClick={() => setOpenModal(false)}>Cancelar</button><button type="button" className="btn-primary" onClick={handleOpenSubmit(onOpenRegister)} disabled={saving}>{saving && <Spinner size="sm" />} Abrir</button></div>}><form onSubmit={handleOpenSubmit(onOpenRegister)} className="space-y-4"><div><label className="label">Saldo Inicial *</label><input type="number" min="0" step="1000" className={`input-field ${openErrors.openingBalance ? 'input-error' : ''}`} {...regOpen('openingBalance', { valueAsNumber: true })} /></div></form></Modal>
    <Modal open={closeModal} onClose={() => setCloseModal(false)} title="Cerrar Caja" size="sm" footer={<div className="flex justify-end gap-2"><button type="button" className="btn-outline" onClick={() => setCloseModal(false)}>Cancelar</button><button type="button" className="btn-destructive" onClick={handleCloseSubmit(onCloseRegister)} disabled={saving}>{saving && <Spinner size="sm" />} Cerrar</button></div>}><form onSubmit={handleCloseSubmit(onCloseRegister)} className="space-y-4"><div className="bg-blue-50 rounded-lg p-4 space-y-2 border border-blue-100"><div className="flex justify-between text-sm"><span className="text-blue-600">Inicial</span><span className="font-medium text-blue-900">{formatCOP(dailyReport?.openingBalance ?? 0)}</span></div><div className="flex justify-between text-sm"><span className="text-green-600">+ Ventas</span><span className="font-medium text-green-700">{formatCOP(dailyReport?.totalSales ?? 0)}</span></div><div className="flex justify-between text-sm"><span className="text-red-600">− Gastos</span><span className="font-medium text-red-700">{formatCOP(dailyReport?.totalExpenses ?? 0)}</span></div><div className="border-t border-blue-200 pt-2 flex justify-between items-center"><span className="text-blue-800 font-semibold text-sm">= Esperado</span><span className="text-2xl font-bold text-blue-900">{formatCOP(dailyReport?.expectedBalance ?? 0)}</span></div></div><div><label className="label">Conteo Físico *</label><input type="number" min="0" step="1000" className={`input-field ${closeErrors.actualBalance ? 'input-error' : ''}`} {...regClose('actualBalance', { valueAsNumber: true })} /></div></form></Modal>
    <Modal open={expenseModal} onClose={() => setExpenseModal(false)} title="Registrar Gasto" size="sm" footer={<div className="flex justify-end gap-2"><button type="button" className="btn-outline" onClick={() => setExpenseModal(false)}>Cancelar</button><button type="button" className="btn-primary" onClick={handleExpSubmit(onCreateExpense)} disabled={saving}>{saving && <Spinner size="sm" />} Guardar</button></div>}><form onSubmit={handleExpSubmit(onCreateExpense)} className="space-y-4"><div><label className="label">Concepto *</label><input className={`input-field ${expErrors.concept ? 'input-error' : ''}`} {...regExp('concept')} /></div><div><label className="label">Monto *</label><input type="number" min="0" step="1000" className={`input-field ${expErrors.amount ? 'input-error' : ''}`} {...regExp('amount', { valueAsNumber: true })} /></div><div><label className="label">Método</label><select className="input-field" {...regExp('paymentMethod')}>{PAYMENT_METHODS.map(m => <option key={m.value} value={m.value}>{m.label}</option>)}</select></div></form></Modal>
    <Modal open={depositModal} onClose={() => setDepositModal(false)} title="Depósito" size="sm" footer={<div className="flex justify-end gap-2"><button type="button" className="btn-outline" onClick={() => setDepositModal(false)}>Cancelar</button><button type="button" className="btn-primary" onClick={onCreateDeposit} disabled={saving}>{saving && <Spinner size="sm" />} Guardar</button></div>}><div className="space-y-4"><div><label className="label">Monto *</label><input type="number" min="0" step="1000" className="input-field" value={depositForm.amount} onChange={e => setDepositForm(f => ({ ...f, amount: e.target.value }))} /></div><div><label className="label">Banco *</label><input className="input-field" value={depositForm.bankName} onChange={e => setDepositForm(f => ({ ...f, bankName: e.target.value }))} /></div><div><label className="label">Referencia</label><input className="input-field" value={depositForm.reference} onChange={e => setDepositForm(f => ({ ...f, reference: e.target.value }))} /></div><div><label className="label">Fecha</label><input type="date" className="input-field" value={depositForm.depositDate} onChange={e => setDepositForm(f => ({ ...f, depositDate: e.target.value }))} /></div></div></Modal>
  </div>)
}
